resolver: lts-9.2
packages:
- '.'
extra-deps:
- 'dhall-1.5.1'
- 'xmlhtml-0.2.5'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

